# An array of random numbers
- The random() function returns random numbers in the half-open interval [0.0,1.0).The half - open interval includes 0 but excludes 1. The required number of random numbers is passed through the 'size' parameter

# random
# randint
# randn

In [2]:
import numpy as np

In [15]:
np.random.random(10) # random values between 0 to 1

array([0.76975677, 0.00397151, 0.24322263, 0.37767044, 0.76568172,
       0.98231951, 0.19520465, 0.48450472, 0.50588588, 0.14357461])

In [17]:
np.random.randn(10) # random values between -3 to +3 , its a normalization 

array([-0.10794865, -0.48398992,  0.92508356,  0.08780682, -0.45564249,
        0.53189685, -0.84108173,  0.9710348 , -0.83477054,  0.3584836 ])

In [14]:
np.random.randint(1,10,5) # random values of given range

array([2, 3, 3, 1, 7], dtype=int32)

In [18]:
l1 = [1,2,3,4]
l2 = [11,12,13]
for x,y in zip(l1,l2):
    print(x+y)

12
14
16


In [23]:
l1 = [1,2,3,4]
l2 = [11,12,13]
for x,y in zip(l1,l2):
    print(x*y)

11
24
39


In [28]:
# addition


l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1+l2

array([12, 14, 16, 18])

In [30]:
# Subraction



l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1-l2

array([-10, -10, -10, -10])

In [31]:
# Multiplication
l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1*l2

array([11, 24, 39, 56])

In [32]:
# Division
l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1/l2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [33]:
# floor division
l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1//l2

array([0, 0, 0, 0])

In [34]:
# Modulo division
l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1%l2

array([1, 2, 3, 4])

In [35]:
#Comparision
l1 = [1,2,3,4]
l2 = [11,12,13,14]
l1 = np.array(l1)
l2 = np.array(l2)
l1==l2

array([False, False, False, False])

# Brodcasting

In [36]:
l1+10

array([11, 12, 13, 14])

In [37]:
l1 - 1

array([0, 1, 2, 3])

In [38]:
l1*5

array([ 5, 10, 15, 20])

In [39]:
l1/2

array([0.5, 1. , 1.5, 2. ])

In [40]:
l1//5

array([0, 0, 0, 0])

In [41]:
l1%6

array([1, 2, 3, 4])

In [48]:
l1==3

array([False, False,  True, False])

 # **Note:-** 
 - Array size is different , operations are not possible

In [49]:
l2>13

array([False, False, False,  True])

In [50]:
l2 != 12

array([ True, False,  True,  True])

In [54]:
l2[l2>12]  # fetching the true values i.e return greater than 12 values

array([13, 14])

In [60]:
l2[l2%2==0]

array([12, 14])

In [61]:
l1[l2%2==0]

array([2, 4])

In [64]:
l1 = np.array([1,2,3,4])
l2 = np.array([4,5,6,7])

In [66]:
print(l1/l2)

[0.25       0.4        0.5        0.57142857]


In [70]:
arr = np.arange(1,10)
arr[arr%2 != 0]

array([1, 3, 5, 7, 9])

# Intializing the Arthematic operation on 2 Dimension arrays

In [105]:
l1 = np.arange(1,5,1).reshape(2,2)
l2 = np.arange(5,9,1).reshape(2,2)
print(l1)
print(l2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [106]:
l1+l2  # 1+5 = 6 , 2+6 = 8, 3+7 = 10 , 4+8 = 12

array([[ 6,  8],
       [10, 12]])

In [107]:
l1-l2


array([[-4, -4],
       [-4, -4]])

In [108]:
l1*l2

array([[ 5, 12],
       [21, 32]])

In [109]:
l1/l2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [110]:
l1//l2

array([[0, 0],
       [0, 0]])

In [111]:
l1%l2

array([[1, 2],
       [3, 4]])

In [112]:
l1==l2

array([[False, False],
       [False, False]])

In [113]:
l1[l1>=3]

array([3, 4])

# Matrix multiplication
1) col count of array1 = row count of array2
2) resultant array shape = (row count of array1,col count of array2)

In [114]:
l1@l2

array([[19, 22],
       [43, 50]])

# Transpose matrix

In [115]:
l1.T

array([[1, 3],
       [2, 4]])

In [138]:
l1 = np.eye(3,3)
l2 = np.random.randint(1,10,9).reshape(3,3)
l2

array([[6, 6, 9],
       [8, 5, 6],
       [1, 5, 9]], dtype=int32)

In [139]:
l1*l2

array([[6., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [140]:
l1@l2

array([[6., 6., 9.],
       [8., 5., 6.],
       [1., 5., 9.]])

In [141]:
l1 = np.arange(1,10,1)
l1.sum()

np.int64(45)

In [142]:
np.max(l1)

np.int64(9)

In [143]:
l1.min()

np.int64(1)

In [144]:
l2.max()

np.int32(9)

In [145]:
l2.min()

np.int32(1)

In [147]:
l1.sort()
l1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
l2.sort()
l2

array([[6, 6, 9],
       [5, 6, 8],
       [1, 5, 9]], dtype=int32)

In [166]:
l1 = np.arange(1,10,1).reshape(3,3)
print(l1)
l1.sum(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [155]:
l1.min(axis = 1)

array([1, 4, 7])

In [156]:
l1.max(axis =1)

array([3, 6, 9])

# axis = 0 ---->  column element sums ----> horizontal elements
# axis = 1 ----> row elemnts sums ----> vertical elemnts

In [179]:
l1 = np.arange(1,10,1).reshape(3,3)
print(l1)
print(l1.sum())
print(l1.max())
print(l1.min())

print(l1.sum(axis = 1))
print(l1.sum(axis = 0))
print(l1.max(axis = 1))
print(l1.max(axis = 0))
print(l1.min(axis = 1))
print(l1.min(axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
9
1
[ 6 15 24]
[12 15 18]
[3 6 9]
[7 8 9]
[1 4 7]
[1 2 3]


In [180]:
l1.sort()
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# concatination of arrays
**Syntax:**
- np.concat(list/tuple of array,axis=0)
- np.vstack(list of array)
  
**Condtiton**

- column count nneds to be equal


In [35]:
arr1 = np.arange(1,10,1).reshape(3,3)
arr2 = np.arange(11,20,1).reshape(3,3)
print("Arr1-----------\n",arr1)
print("Arr2---------\n",arr2)
np.concatenate([arr1,arr2],axis = 0)

Arr1-----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Arr2---------
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [36]:
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [38]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [25]:
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,23,1).reshape(4,3)
print(arr1)
print(arr2)
np.concatenate([arr1,arr2],axis = 0)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [43]:
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,17,1).reshape(2,3)
print(arr1)
print(arr2)
print("------------------------------------")
print(np.concatenate([arr1,arr2],axis = 1))
print("------------------------------------")
print(np.hstack([arr1,arr2]))

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
------------------------------------
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]
------------------------------------
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [28]:
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,17,1).reshape(2,3)
print(arr1)
print(arr2)
np.concatenate([arr1,arr2],axis = 0)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [57]:
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,23,1).reshape(4,3)
print(arr1)
print(arr2)
np.vsplit(arr2,2)
#np.concatenate([arr1,arr2],axis = 1)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


[array([[11, 12, 13],
        [14, 15, 16]]),
 array([[17, 18, 19],
        [20, 21, 22]])]

# Split
1. hsplit - draw a vertical line to split them equally
2. vsplit - draw a horizontal line to split them equally

In [44]:
arr1 = np.arange(1,10,1).reshape(3,3)
np.vsplit(arr1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [50]:
arr2 = np.arange(1,17,1).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [52]:
np.vsplit(arr2,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [55]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
np.hsplit(arr2,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [54]:
np.hsplit(arr2,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [62]:
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(1,16,1).reshape(5,3)
print(arr1)
print(arr2)
np.vstack([arr1,arr2])

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [64]:
arr1 = np.arange(1,21,1).reshape(5,4)
arr2 = np.arange(1,16,1).reshape(5,3)
print(arr1)
print(arr2)
np.hstack([arr1,arr2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


array([[ 1,  2,  3,  4,  1,  2,  3],
       [ 5,  6,  7,  8,  4,  5,  6],
       [ 9, 10, 11, 12,  7,  8,  9],
       [13, 14, 15, 16, 10, 11, 12],
       [17, 18, 19, 20, 13, 14, 15]])

In [69]:
arr = np.arange(1,17,1).reshape(4,4)
print(arr)
np.hsplit(arr,2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [71]:
arr = np.arange(1,17,1).reshape(4,4)
print(arr)
np.vsplit(arr,4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [72]:
a1 = np.arange(1,10).reshape(3,3)
for i in a1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


# Syntax: np.nditer(array_name)

In [73]:
for i in np.nditer(a1):
    print(i)

1
2
3
4
5
6
7
8
9


In [90]:
# create 2d array/matrix and check the values is even or odd
a1 = np.arange(1,5,1).reshape(2,2)
for i in np.nditer(a1):
    if i%2==0:
        print("even",i)
    else:
        print("odd",i)
      

odd 1
even 2
odd 3
even 4


In [91]:
# create 3d array/matrix and check the values is even or odd
a1 = np.arange(1,10,1).reshape(3,3)
for i in np.nditer(a1):
    if i%2==0:
        print("even",i)
    else:
        print("odd",i)
      

odd 1
even 2
odd 3
even 4
odd 5
even 6
odd 7
even 8
odd 9


In [93]:
a1 = np.array([[1,2],[3,4]])
for i in np.nditer(a1,order='f'):
    print(i)

1
3
2
4


# Frequently used Functions(Generic Functions)

In [94]:
# mean,median
a1 = np.random.randint(1,10,5)
print(a1)

[1 6 2 6 5]


In [95]:
np.mean(a1)

np.float64(4.0)

In [96]:
np.median(a1)

np.float64(5.0)

In [111]:
from scipy import stats
print(stats.mode(a1))

ModeResult(mode=np.int32(6), count=np.int64(2))


In [98]:
np.std(a1)

np.float64(2.0976176963403033)

# variance :- sumation(xi-x(bar))^2/n

In [105]:
print(np.var(a1))

4.4


In [107]:
print(np.sqrt(a1))

[1.         2.44948974 1.41421356 2.44948974 2.23606798]


# Flatten()
- Converts the array into 1-dimension array

In [113]:
a1.flatten()

array([1, 6, 2, 6, 5], dtype=int32)

# Linspace 
- np.linspace(start,stop,no of values)
- it gices array of values of equal difference

In [114]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [115]:
np.linspace(1,9,4)

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [117]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [118]:
np.argmax(arr1)

np.int64(19)

In [119]:
np.argmin(arr1)

np.int64(0)

In [126]:
a2 = np.array([5,4,3,1,2])
index = a2.argsort()
print(index)

[3 4 2 1 0]


In [127]:
a2[index]

array([1, 2, 3, 4, 5])

# astype
Syntax:- array[index] = new_value

In [129]:
a2.astype(float)

array([5., 4., 3., 1., 2.])

In [130]:
a2.astype(np.int32)

array([5, 4, 3, 1, 2], dtype=int32)

In [131]:
a2.astype(np.int64)

array([5, 4, 3, 1, 2])

In [132]:
a2.astype(np.float32)

array([5., 4., 3., 1., 2.], dtype=float32)

In [133]:
a2.astype(np.float64)

array([5., 4., 3., 1., 2.])

In [134]:
a2.astype(bool)

array([ True,  True,  True,  True,  True])

In [135]:
a2.astype(complex)

array([5.+0.j, 4.+0.j, 3.+0.j, 1.+0.j, 2.+0.j])

# insert
Syntax:- np.insert(array,values,axis=None)

In [7]:
arr = np.arange(1,10,1).reshape(3,3)
np.insert(arr,7,200)

array([  1,   2,   3,   4,   5,   6,   7, 200,   8,   9])

In [3]:
import numpy as np
arr2 = np.arange(1,10,1).reshape(3,3)
print(arr2)
np.insert(arr2,2,100,axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 100, 100],
       [  7,   8,   9]])

# append
**Syntax**:- np.append(array,values,axis = None)

In [8]:
np.append(arr,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

In [9]:
np.append(arr2,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

# Delete
**Syntax**:- np.delete(array,obj,axis = None)

In [10]:
np.delete(arr2,0)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2 = np.arange(1,10).reshape(3,3)
np.delete(arr2,0,axis = 0)


array([[4, 5, 6],
       [7, 8, 9]])

# Where
**Syntax**:- np.where(condition,x,y)

In [21]:
arr = np.arange(1,10,1).reshape(3,3)
np.where(arr>5,"Yes","No")

array([['No', 'No', 'No'],
       ['No', 'No', 'Yes'],
       ['Yes', 'Yes', 'Yes']], dtype='<U3')

# **&** ----> and
# **|** ---> or

In [25]:

print(np.where((arr>2)&(arr<6)))
np.where((arr>2)|(arr<6))

(array([0, 1, 1]), array([2, 0, 1]))


(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

# any
**Syntax**:- array.any(axis=None,out=None,keepdims=False)

In [28]:
np.array([False,False,False]).any()

np.False_

# all
**Syntax**:- array.all(axis=None,out=None,keepdims=False)

In [31]:
np.array([True,True,True]).all()

np.True_